/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productos;

import Principal.Administrador;
import static Principal.Administrador.tablaProductos;
import Principal.conectar;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author peto7
 */
public class ModificarProducto extends javax.swing.JDialog {
        boolean encontrado=false;
        String catnombre="";
        String catdescripcion="";
//String idproducto2;
        //}catch(Exception e){
            
        //}
     
    /**
     * Creates new form ModificarProducto
     */
    public ModificarProducto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(Administrador.Paneles);
        int filaseleccionada = tablaProductos.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) Administrador.tablaProductos.getModel();
        idproducto.setText(tablaProductos.getValueAt(filaseleccionada, 0).toString());
        prodnombre.setText(tablaProductos.getValueAt(filaseleccionada, 1).toString());
        prodprecio.setText(tablaProductos.getValueAt(filaseleccionada, 2).toString());
        prodescuento.setText(tablaProductos.getValueAt(filaseleccionada, 3).toString());
//        prodstock.setText(tablaProductos.getValueAt(filaseleccionada, 4).toString());
        prodexistencia.setText(tablaProductos.getValueAt(filaseleccionada, 4).toString());
        idcategoria.setText(tablaProductos.getValueAt(filaseleccionada, 5).toString());
        idproducto.setTransferHandler(null);
        prodnombre.setTransferHandler(null);
        prodprecio.setTransferHandler(null);
        prodescuento.setTransferHandler(null);
        idcategoria.setTransferHandler(null);
    }
    
    int x,y;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        idcategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prodexistencia = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prodescuento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        prodprecio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        prodnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idproducto = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 29, 116), 3, true));

        jButton1.setBackground(new java.awt.Color(197, 29, 116));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar");
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        idcategoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        idcategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                idcategoriaFocusLost(evt);
            }
        });
        idcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcategoriaActionPerformed(evt);
            }
        });
        idcategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idcategoriaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ID Categoria:");

        prodexistencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodexistencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodexistenciaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Existencia:");

        prodescuento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodescuentoKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Descuento:");

        prodprecio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodprecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodprecioKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Precio:");

        prodnombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        prodnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prodnombreKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        idproducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Producto:");

        jButton2.setBackground(new java.awt.Color(197, 29, 116));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setOpaque(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(197, 29, 116));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Modificar Producto");
        jLabel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel9MouseDragged(evt);
            }
        });
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(idcategoria))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prodnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(prodprecio)
                            .addComponent(prodescuento)
                            .addComponent(prodexistencia))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prodexistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //boolean var;
            //var=Guardar();
            if (Guardar()){
                this.dispose();                
            }
        } catch (SQLException ex) {
            Logger.getLogger(ModificarProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean Guardar() throws SQLException{
        boolean a = false;
       // boolean encontrado=false;
        
      /*  int contador=0;
        String cadena2=prodnombre.getText();
        Pattern pat2 = Pattern.compile("[A-Z]?[a-zñ[áéíóú]?]+(([\\s][A-Z]?[a-zñ[áéíóú]?]+)?)+$");
        Matcher mat2 = pat2.matcher(cadena2);
        if (mat2.matches()) {
            prodnombre.setBackground(Color.white);
            nombre.setText("");
            contador=contador+1;
        } else {
            prodnombre.setBackground(Color.pink);
            nombre.setText("Debe contener solo letras y espacios opcionales");
            nombre.setForeground(Color.red);
     }
        String cadena4=prodprecio.getText();
        Pattern pat4 = Pattern.compile("([0-9]{1,5}([.][0-9]{1,2})?)$");
        Matcher mat4 = pat4.matcher(cadena4);
        if (mat4.matches()) {
            prodprecio.setBackground(Color.white);
            precio.setText("");
            contador=contador+1;
        } else {
            prodprecio.setBackground(Color.pink);
            precio.setText("Deben ser solo numeros y puede llevar punto decimal"); 
            precio.setForeground(Color.red);
     }
        String cadena5=prodescuento.getText();
       // Pattern pat5 = Pattern.compile("[0-9]+([.][0-9]+)?$");
        Matcher mat5 = pat4.matcher(cadena5);
        if (mat5.matches()) {
            prodescuento.setBackground(Color.white);
            descuento.setText("");
            contador=contador+1;
        } else {
            prodescuento.setBackground(Color.pink);
            descuento.setText("Deben ser solo numeros y puede llevar punto decimal");
            descuento.setForeground(Color.red);
     }
        String cadena3=prodexistencia.getText();
        Pattern pat3 = Pattern.compile("[0-9]{1,4}$");
        Matcher mat3 = pat3.matcher(cadena3);
        if (mat3.matches()) {
            prodexistencia.setBackground(Color.white);
            existencia.setText("");
            contador=contador+1;
        } else {
            prodexistencia.setBackground(Color.pink);
            existencia.setText("Deben ser solo numeros y puede llevar punto decimal");
            existencia.setForeground(Color.red);
     }
        String cadena9=catnombre.getText();
       // Pattern pat9 = Pattern.compile("[a-zñ[áéíóú]?]+$");
        Matcher mat9 = pat2.matcher(cadena9);
        if (mat9.matches()) {
            catnombre.setBackground(Color.white);
            nombrecat.setText("");
            contador=contador+1;
        } else {
            catnombre.setBackground(Color.pink);
            nombrecat.setText("Debe contener solo letras y espacios opcionales");
            nombrecat.setForeground(Color.red);
        }
        if(contador==5){  */
                
    /*    String sql2="SELECT catnombre, catdescripcion FROM productos WHERE idcategoria='"+idcategoria.getText()+"'";
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql2);
            
            while(rs.next()){
                encontrado=true;
                //JOptionPane.showMessageDialog(null,"El ID ya existe!");   
                catnombre=rs.getString("catnombre");
                catdescripcion=rs.getString("catdescripcion");
            }
            if (encontrado==false){
                JOptionPane.showMessageDialog(null,"ID de la categoria no encontrado, es necesario registrarlo!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }*/
      
      
      if (encontrado==true){
          try{            
            String sql = "UPDATE productos SET idproducto=?, prodnombre=?, prodcantidad=?, prodprecio=?, prodescuento=?, prodexistencia=?, idcategoria=?, catnombre=?, catdescripcion=? WHERE idproducto='"+idproducto.getText()+"'" ;
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1,idproducto.getText());
            pst.setString(2,prodnombre.getText());
            pst.setString(3,prodexistencia.getText());
            pst.setString(4,prodprecio.getText());
            pst.setString(5,prodescuento.getText());
            pst.setString(6,prodexistencia.getText());
            pst.setString(7,idcategoria.getText());
            pst.setString(8,catnombre);
            pst.setString(9,catdescripcion);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Actualizados Correctamente!");
            /*idproducto.setText("");
            prodnombre.setText("");
            prodprecio.setText("");
            prodescuento.setText("");
            prodexistencia.setText("");
            catnombre.setText("");*/
            a=true;
        }catch(HeadlessException | SQLException e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null,"Ocurrio un problema!");
        }
        /*}else{            
            JOptionPane.showMessageDialog(null,"ERROR AL GUARDAR PRODUCTO!");
            a=false;         
        }*/
        DefaultTableModel modelo = (DefaultTableModel) tablaProductos.getModel();
        int filas = tablaProductos.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
            productos.tablaproducto ver = new productos.tablaproducto();
        ver.mostrardato();        
    }
      return a;
      }
        
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jLabel9MouseDragged

    private void prodnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodnombreKeyTyped
        if (!Character.isLetter(evt.getKeyChar())
                && !(evt.getKeyChar() == KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_prodnombreKeyTyped

    private void prodprecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodprecioKeyTyped
        char c = evt.getKeyChar();
        if(((c<'0' || c>'9')) && (c !=KeyEvent.VK_BACK_SPACE) && (c !='.')){
            evt.consume();
        }
    }//GEN-LAST:event_prodprecioKeyTyped

    private void prodescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodescuentoKeyTyped
        int caracteres=3;
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
        if(prodescuento.getText().length()>=caracteres){
           evt.consume();
        }
    }//GEN-LAST:event_prodescuentoKeyTyped

    private void prodexistenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prodexistenciaKeyTyped
        int caracteres=4;
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
        if(prodexistencia.getText().length()>=caracteres){
           evt.consume();
        }
    }//GEN-LAST:event_prodexistenciaKeyTyped

    private void idcategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idcategoriaKeyTyped
        int caracteres=5;
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
        if(idcategoria.getText().length()>=caracteres){
           evt.consume();
        }
    }//GEN-LAST:event_idcategoriaKeyTyped

    private void idcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcategoriaActionPerformed
        String sql="SELECT catnombre, catdescripcion FROM productos WHERE idcategoria='"+idcategoria.getText()+"'";
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
           // boolean encontrado=false;
            while(rs.next()){
                encontrado=true;
                //JOptionPane.showMessageDialog(null,"El ID ya existe!");   
                catnombre=rs.getString("catnombre");
                catdescripcion=rs.getString("catdescripcion");
            }
            if (encontrado==false){
                JOptionPane.showMessageDialog(null,"ID de la categoria no encontrado, es necesario registrarlo!");
                idcategoria.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_idcategoriaActionPerformed

    private void idcategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idcategoriaFocusLost
        String sql="SELECT catnombre, catdescripcion FROM productos WHERE idcategoria='"+idcategoria.getText()+"'";
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
         //   boolean encontrado=false;
            while(rs.next()){
                encontrado=true;
                //JOptionPane.showMessageDialog(null,"El ID ya existe!");   
                catnombre=rs.getString("catnombre");
                catdescripcion=rs.getString("catdescripcion");
            }
            if (encontrado==false){
                JOptionPane.showMessageDialog(null,"ID de la categoria no encontrado, es necesario registrarlo!");
                idcategoria.requestFocus();
            }
        } catch (SQLException ex) {
            Logger.getLogger(NuevoProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_idcategoriaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarProducto dialog = new ModificarProducto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
        conectar cc= new conectar();
        Connection cn=cc.conexion();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idcategoria;
    private javax.swing.JLabel idproducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField prodescuento;
    private javax.swing.JTextField prodexistencia;
    private javax.swing.JTextField prodnombre;
    private javax.swing.JTextField prodprecio;
    // End of variables declaration//GEN-END:variables
}
