/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import Principal.Administrador;
import static Principal.Administrador.CheckAdvertenciaPocoStock;
import static Principal.Administrador.subtotalventas;
import static Principal.Administrador.tablaVentas;
import static Principal.Administrador.totalpesos;
import Principal.conectar;
import javax.swing.JOptionPane;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Yonathan
 */
public class RealizarVenta extends javax.swing.JDialog {

    /**
     * Creates new form RealizarVentas2
     */
    public RealizarVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(Administrador.Paneles);
    }
//    String ExistenciaInicial [];
//    ExistenciaInicial = new String[3];
    String[] ExistenciaInicial = new String[50];
    String[] ProductosVendidos = new String[50];
    public static double totale;
    int x, y;
    int id_venta;
    double AuxCambio;
    conectar cc = new conectar();
    Connection cn = cc.conexion();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totalrealizar = new javax.swing.JLabel();
        importe = new javax.swing.JTextField();
        txtcambio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(197, 29, 116), 3, true));

        jPanel2.setBackground(new java.awt.Color(197, 29, 116));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Realizar venta");
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        btn1.setBackground(new java.awt.Color(197, 29, 116));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setText("Cancelar");
        btn1.setContentAreaFilled(false);
        btn1.setFocusPainted(false);
        btn1.setOpaque(true);
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Cambio:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Importe:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Total:");

        totalrealizar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        importe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        importe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                importeKeyTyped(evt);
            }
        });

        txtcambio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(importe, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(totalrealizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(totalrealizar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(importe))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtcambio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        if (btn1.getText().equals("Cerrar")) {
            try {
                DefaultTableModel modelo = (DefaultTableModel) tablaVentas.getModel();
                int filas = tablaVentas.getRowCount();
                for (int i = 0; filas > i; i++) {
                    modelo.removeRow(0);
                } 
            } catch (Exception e) {
                System.out.println("ERROR: " + e);
            }
            Administrador.contadordeceldas = 0;
            subtotalventas = 0;
            totalpesos.setText(String.valueOf(subtotalventas));
            ventas.OpcionesVentas.numerosVenta();
            this.dispose();
            
            boolean var = PocoStockMetodo();
            if (var && CheckAdvertenciaPocoStock.isSelected()) {
                PocoStock abrir = new PocoStock(new JFrame(), true);
                abrir.setVisible(true);
            }
        } else {
            dispose();
        }
        
    }//GEN-LAST:event_btn1ActionPerformed

    private void importeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_importeKeyTyped
                double importevar = 0;
//                cambio=0;
                int caracteres = 12;//100,000,000,000
                char c = evt.getKeyChar();
                if (c < '0' || c > '9' && !(evt.getKeyChar() == KeyEvent.VK_PERIOD)) {
                        evt.consume();  //Limita solo la escritura de numeros en el jtextfield
                    }
                if (importe.getText().length() >= caracteres) { //Limita a 13 digitos numericos
                        evt.consume();
                    }
                if ((c == KeyEvent.VK_ENTER)) {
                        importevar = Double.parseDouble(importe.getText());
                        if (importevar < totale) {
                                JOptionPane.showMessageDialog(this, "Error: Importe debe ser mayor a Total.");
                                txtcambio.setText("");
                            } else {
                            ChecarStock();
                                double cambio = (importevar - totale);
                                AuxCambio = cambio;
                                NumberFormat nf = NumberFormat.getCurrencyInstance(Locale.getDefault());
                                txtcambio.setText(nf.format(cambio));
                                importe.setEditable(false);
                                btn1.setText("Cerrar");
                                registrarventa();
                                btn1.requestFocus();
//                                ActualizarStock();
                            }
                    }
    }//GEN-LAST:event_importeKeyTyped

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        Point mueve = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(mueve.x - x, mueve.y - y);
    }//GEN-LAST:event_jLabel1MouseDragged

        public void registrarventa() {
        ventas.Sentencias s = new Sentencias();
        int contador = 0;
        for (int i = 0; i < Administrador.tablaVentas.getRowCount(); i++) {
            s.setId_venta(Integer.parseInt(Administrador.numVenta.getText()));
            id_venta = Integer.parseInt(Administrador.numVenta.getText());
            s.setNom_producto(Administrador.tablaVentas.getValueAt(i, 1).toString());
            s.setPrecioArt(Administrador.tablaVentas.getValueAt(i, 4).toString());
            s.setNomVendedor(Administrador.lbNombreVendedor.getText());
            s.setNomCliente(Administrador.NombreCliente.getText());
            s.setDescuento(Administrador.tablaVentas.getValueAt(i, 5).toString());
            s.setFecha(Administrador.fecha.getText());
            s.setTotal(Double.parseDouble(Administrador.tablaVentas.getValueAt(i, 6).toString()));
            s.setCantidad(Integer.parseInt(Administrador.tablaVentas.getValueAt(i, 3).toString()));
            s.setImporte(Integer.parseInt(importe.getText()));
            s.setCambio(String.valueOf(AuxCambio));
            s.setTotalVenta(Administrador.totalpesos.getText());
            int opcion = ventas.OpcionesVentas.registrar(s);
            if (opcion != 0) {
                contador++;
            }
        } 

        if (contador == Administrador.tablaVentas.getRowCount()) {
//            GenerarTicket.ticket(id_venta);
//    public void ticket(int id){
        try {
            conectar cc = new conectar();
        java.sql.Connection cn = cc.conexion();
            
            JasperReport reporte = null;
            String path = "src\\ticket\\ticket.jasper";
            
//            InputStream is=this.getClass().getResourceAsStream("/com/medicam/servlets/Invoice.jrxml");
//            JasperReport jasperReport = JasperCompileManager.compileReport(is);
            
            Map parametro = new HashMap();
            parametro.put("id_venta", id_venta);
            
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, cn);
            
            
            JasperViewer view = new JasperViewer(jprint, false);
//            JasperPrintManager.printReport(jprint, true);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            view.setTitle("Tiket de venta");
            view.setVisible(true);
            
            
            
        } catch (JRException ex) {
            Logger.getLogger(GenerarTicket.class.getName()).log(Level.SEVERE, null, ex);
        }
//    }
        }
    }
        
    public void ChecarStock() {
        for (int i = 0; i < tablaVentas.getRowCount(); i++) {
            Object idproducto = tablaVentas.getValueAt(i, 0);
            String id = String.valueOf(idproducto);
//            System.out.println("Codigo: " + id);
            
            ProductosVendidos [i] = String.valueOf(tablaVentas.getValueAt(i, 3));
//            System.out.println("Vendidos: "+ProductosVendidos[i]);
            try {
                Statement comando = cn.createStatement();
                ResultSet registro = comando.executeQuery("SELECT prodexistencia FROM productos WHERE idproducto = " + id);
                if (registro.next() == true) {
                    ExistenciaInicial[i] = registro.getString("prodexistencia");
//                    System.out.println("Existencia: " + ExistenciaInicial[i]);
                }
            } catch (Exception e) {
                System.out.println("ERROR: " + e);
            }
        }
    }
    
    public void ActualizarStock(){
        for (int i = 0; i < tablaVentas.getRowCount(); i++) {
            Object idproducto = tablaVentas.getValueAt(i, 0);
            String id = String.valueOf(idproducto);
//            System.out.println("Codigo: " + id);
           try{ 
            String sql = "UPDATE productos SET prodexistencia=? WHERE idproducto = '"+id+"'";
            PreparedStatement pst = cn.prepareStatement(sql);
            int existencia = Integer.parseInt(ExistenciaInicial[i]);
            int vendidos = Integer.parseInt(ProductosVendidos [i]);
            int totalExistenciaNow = existencia-vendidos;
//               System.out.println("NOW: "+totalExistenciaNow);
            pst.setString(1,String.valueOf(totalExistenciaNow));
            pst.executeUpdate();
           }catch(Exception e){
            System.out.println("ERROR: "+e);
        }
    }
    }
    
    public boolean PocoStockMetodo() {
        boolean var = false;
        try {
            Statement comando = cn.createStatement();
            ResultSet registro = comando.executeQuery("SELECT * FROM productos WHERE prodexistencia <= 2");
            if (registro.next() == true) {
                var = true;
            }else{
                var = false;
            }
        } catch (Exception e) {
            System.out.println("ERROR: " + e);
        }
        return var;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealizarVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RealizarVenta dialog = new RealizarVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    public static javax.swing.JTextField importe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel totalrealizar;
    private javax.swing.JLabel txtcambio;
    // End of variables declaration//GEN-END:variables
}
